version: "3.8"
services:
  mysql:
    image: mysql:8.0.33
    env_file: ./.env
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80


volumes:
  db:
  